# Global configuration for Prometheus scraping jobs:

:global:
  # How often Prometheus scrapes targets for metrics (15 seconds in this case):
  scrape_interval: 15s

  # Additional labels added to all scraped metrics:
  # - Identifies them as belonging to the 'prometheus' monitoring system:
  external_labels:
    monitor: 'prometheus'

# List of individual scraping jobs:

scrape_configs:
  # This job is named 'prometheus':
  - job_name: 'prometheus'

    # Uses static configuration to define targets:
    static_configs:
      # Scrapes metrics from the Prometheus server running on localhost:9090:
      - targets: ['localhost:9090']
